{% set name = "kalker" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PaddiM8/kalker/archive/v{{ version }}.tar.gz
  sha256: 4f34d34e922308e586fd9f7077e1cba126f3e75d269f4859d0472bb565ce1d4d

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    # - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - m4
    - make
  host:
    - gmp
    - mpc
    - mpfr

test:
  commands:
    - kalker --help

about:
  home: https://github.com/PaddiM8/kalker
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Full-featured calculator with math syntax
  dev_url: https://github.com/PaddiM8/kalker

extra:
  recipe-maintainers:
    - danielnachun
