{% set name = "kalker" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PaddiM8/kalker/archive/v{{ version }}.tar.gz
  sha256: a6ccf096301a37d2bbb14fdacfc8c801a8b058b0fd38929639d03c4868564adf

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - m4
    - make

test:
  commands:
    - kalker --help

about:
  home: https://github.com/PaddiM8/kalker
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Full-featured calculator with math syntax
  dev_url: https://github.com/PaddiM8/kalker

extra:
  recipe-maintainers:
    - danielnachun
